### ISSUE TITLE
Starting from a cell-by-bin read count matrix

### ISSUE THREAD

**Issue by pedrofale** [raphael-group/chisel#10]
Hello,

Thanks for this great tool! I would like to use CHISEL on a cell-by-bin read count matrix to simply call copy numbers. What's the easiest way to achieve this?

**Comment by simozacca** [comment]
Thank you for the interest in CHISEL!

CHISEL can be directly run starting from read counts in genomic bins and phased SNP read counts per cell. According to the information already available there are two available ways to do this:

1. If you have phased read counts for every genomic bin, you can simply form a dataframe `combo.tsv` as described [here](https://github.com/raphael-group/chisel/blob/master/doc/chisel.md) and execute CHISEL with the command `chisel_calling`. Otherwise, in case you do not have phased read counts for every genomic bin (the most typical case), please consider option 2.

2. You can format read counts and phased SNP counts as three dataframes with the formats described [here](https://github.com/raphael-group/chisel/blob/master/doc/chisel.md) for the files `total.tsv`, `rdr.tsv`, and `baf.tsv`. Importantly, note that SNPs have to be phased and A/B counts for consecutive SNPs must be defined accordingly (see input data requirements). Once you have these dataframes, you can simply use the program `src/Combiner.py` of CHISEL to combine everything into the dataframe `combo.tsv` (see format [here](https://github.com/raphael-group/chisel/blob/master/doc/chisel.md)) which can be used as direct input for the CHISEL command `chisel_calling`. Using the recommended folder structure and a haplotype-block length of 50kb, these two commands will be sufficient:
```
python src/Combiner.py -r rdr/rdr.tsv -b baf/baf.tsv -k 50kb -l rdr/total.tsv > combo/combo.tsv
chisel_calling combo.tsv
```

As an example, both these procedures can be directly executed with the [published](https://doi.org/10.5281/zenodo.3817605) read and phased SNP counts.

Please note that a cell-by-bin read count is not sufficient but you also need read counts for heterozygous germline SNPs.

**Comment by pedrofale** [comment]
Thanks, but I really just want the total copy number estimates and don't care about allele-specific states. I know there are other tools to do this, but I want to see how CHISEL fares in this case. 

I have built a `combo.tsv` according to the structure described in section "Combining RDRs and BAFs" of https://github.com/raphael-group/chisel/blob/master/doc/chisel.md, and then run `chisel_calling combo.tsv`, and even though I get the outputs in `calls/calls.tsv` and `calls/log`, the `calls/calls.tsv` file is empty. I also tried using the `src/Caller.py` script directly, but it gets killed without any informative error message. What could the issue be?

**Comment by simozacca** [comment]
CHISEL requires phased SNP read counts and, unfortunately, it cannot be used without these because CHISEL integrates BAF in the whole inference, even in the inference of total copy numbers (i.e. in the inference of the scaling factor/genome ploidy). Please find more details about this in the descriptions of the second and third steps of CHISEL in the published article at: https://www.nature.com/articles/s41587-020-0661-6
