### ISSUE TITLE
Python3.x support

### ISSUE THREAD

**Issue by evanbiederstedt** [raphael-group/chisel#2]
Excellent work, @simozacca!

It's probably best to convert this work to python3.x, given the support for python2.7 will end in less than two months. 

Previously, I would try to aim for py23 compatibility, but it's probably best just to rewrite in python3.x

I may be able to write up a PR at some point to aid in this :)

**Comment by simozacca** [comment]
Thank you for the interest in our method! The porting to `python3` is definitely in our plans and any help that can be provided would be very appreciated.

However, for the benefit of CHISEL users, I would like to point out few observations:
1. `python2.7` will not stop working but will not be maintained/updated.
2. Python managers (e.g. Anaconda, virtualenv, etc...) are specifically meant to maintain code written with different python versions in close and stable environments for the future.
3. The use of virtual environments through these python managers remains the highly recommended way to use CHISEL because `python` is an OS language and is very commonly used. Therefore, virtual environments guarantee package independence and full compatibility, in addition to provide a one-line command installation.
4. Python managers are often already available in a machine or can be very easily used and installed in any local environment.

I will keep this thread open until support for Python 3.x will be integrated.

**Comment by evanbiederstedt** [comment]
I agree with each of the comments above, and I'm glad this was explicitly stated to avoid any confusion. 

> 1. python2.7 will not stop working but will not be maintained/updated.

That is certainly true. CHISEL will still work after January 1st 2020 :)

> I will keep this thread open until support for Python 3.x will be integrated.

Excellent. Based on a cursory look, it will not be painful, and I'll try to help out if time allows.

**Comment by simozacca** [comment]
CHISEL has been deposited in [bioconda](https://bioconda.github.io/recipes/chisel/README.html#package-chisel) and transition to python 3 will be carried over accordingly in future releases
