### ISSUE TITLE
abnormal chr2q baf

### ISSUE THREAD

**Issue by robinycfang** [raphael-group/chisel#38]
Dear developer,

Thanks for the useful tool! I have some 10x scDNA data from tumor tissue samples. I don't have paired scDNA from paired normal tissue.  I only have paired PBMC bulk WGS, and also calculated phased SNPs from PBMC against pseudo bulk tumor. I used PMBC as a normal, but the resulting CNVs are very noisy. Then, I tried pseudo normal mode with the same phased SNPs, the CNVs became less noisy but still. Finally, I tried the nonormal mode, with the ART simulation, the CNVs were very clean. However, I have noticed a consistant issue with either pseudo normal or nonormal mode - in baf plot, I noticed that there was always a consistant baf value (0 or 0.5) at chr2q. This is happening to all my samples, not just one. Can you suggest if this is normal? Thanks.

Pseudo normal:

chisel_pseudonormal \
    ${tumor_bam} \
    -r /refdata-GRCh38-1.0.0/fasta/genome.fa \
    --samtools ${SAMTOOLS}

chisel \
    -t ${tumor_bam} \
    -n ./pseudonormal/pseudonormal.bam \
    -r /refdata-GRCh38-1.0.0/fasta/genome.fa \
    -l filtered_snp.tsv \
    --samtools ${SAMTOOLS} \
    --bcftools ${BCFTOOLS}

![image](https://github.com/user-attachments/assets/ecf42840-7b08-403a-85c1-2b0e6a026bf5)

![image](https://github.com/user-attachments/assets/05699a9b-cac9-4a1d-80d9-dcb043c925f4)

Nonormal:

chisel_nonormal \
     -t ${tumor_bam} \
     -r /refdata-GRCh38-1.0.0/fasta/genome.fa \
     -l filtered_snp.tsv \
     --samtools ${SAMTOOLS} \
     --bcftools ${BCFTOOLS} \
     --art /art_bin_MountRainier/art_illumina \
     --bwa /miniconda3/bin/bwa

![image](https://github.com/user-attachments/assets/7c929384-bc37-459c-8ba6-5caccfe72ba8)

![image](https://github.com/user-attachments/assets/aaea7665-235d-40da-896b-37703a005ee8)

**Comment by simozacca** [comment]
Thank you for your message. Yes, a constant 0-value BAF value is inferred in large genomic regions in which heterozygous SNPs are not observed in tumour cells at any allelic frequency, and these regions are thus assumed to be affected by LOHs (since such large regions are unlikely to not contain enough heterozygous SNPs). This is the strategy used to infer BAF by the nonormal version when SNPs genotyped from whole-genome sequencing of matched normal samples is not available.

Your plots appear to be reasonable and consistent, only one note: from the no-normal version you seem to have reported the clone copy numbers, rather than cell-specific copy numbers, that will generally display also some cell-specific variations.

Please feel free to re-open the issue if you have other related questions.

**Comment by robinycfang** [comment]
> Thank you for your message. Yes, a constant 0-value BAF value is inferred in large genomic regions in which heterozygous SNPs are not observed in tumour cells at any allelic frequency, and these regions are thus assumed to be affected by LOHs (since such large regions are unlikely to not contain enough heterozygous SNPs). This is the strategy used to infer BAF by the nonormal version when SNPs genotyped from whole-genome sequencing of matched normal samples is not available.
> 
> Your plots appear to be reasonable and consistent, only one note: from the no-normal version you seem to have reported the clone copy numbers, rather than cell-specific copy numbers, that will generally display also some cell-specific variations.
> 
> Please feel free to re-open the issue if you have other related questions.

Thank you so much for your reply!

The SNPs were called from the paired bulk PBMC WGS with pseudo-bulk scWGS, and each patient had >2M het SNPs. I am a bit suprised that none of them were seen in the paired scWGS. The other thing I am concerned about is that I have scWGS from 10 patients, and baf of 0 or 0.5 on chr2q is happening in ALL cells and ALL patients. This consistent LOH seems unlikely to me. Also, the tumor cells were enriched using columns, but there should still be some normal cells in the samples, so such frequent LOH shouldn't happen in all cells, since there are also normal cells.

Do you think I should recall SNPs from scWGS only, using the pipeline you provided? Or is there anything else I can try? Depending on the plots I showed, which mode do you think is better, pseudo or nonormal? May pseudo is better, as nonormal didn't idenitfy any diploidy normal cells that indeed existed?

I thought the cbaf.png shows for per cell? Each dot is one bin per cell?

Maybe this plot is more clear for chr2q, this is happening to all my 10 scWGS.

![image](https://github.com/user-attachments/assets/ff1c03d1-b2a7-4854-bb99-bde42c04928e)

Thanks again!

**Comment by simozacca** [comment]
Having only a few normal cells will not be generally enough to genotype a sufficient number of SNPs in LOH genomic regions, since many of them will be missed due to the low frequency. However, it is weird what's happening on chromosome 2, as it seems that no SNP has been identified at all, and you can compare your SNPs with what you'd obtain by regenotyping the same loci in the scWGS data, treating the scWGS as a pseudobulk sample.

In any case, based on your results I would recommend using the psedunormal approach as these results look quite good and not so much noisier than expected. You can further improve the ploidy calls for outlying cells but tuning `-A` paramter as explained in the [ploidy guide](https://github.com/raphael-group/chisel/blob/master/guides/ploidy.md). Also, in order to get good clones (that are currently failing) you would need to tune the cloning-step paramters according to your data following the [cloning guide](https://github.com/raphael-group/chisel/blob/master/guides/clones.md).

**Comment by robinycfang** [comment]
> Having only a few normal cells will not be generally enough to genotype a sufficient number of SNPs in LOH genomic regions, since many of them will be missed due to the low frequency. However, it is weird what's happening on chromosome 2, as it seems that no SNP has been identified at all, and you can compare your SNPs with what you'd obtain by regenotyping the same loci in the scWGS data, treating the scWGS as a pseudobulk sample.
> 
> In any case, based on your results I would recommend using the psedunormal approach as these results look quite good and not so much noisier than expected. You can further improve the ploidy calls for outlying cells but tuning `-A` paramter as explained in the [ploidy guide](https://github.com/raphael-group/chisel/blob/master/guides/ploidy.md). Also, in order to get good clones (that are currently failing) you would need to tune the cloning-step paramters according to your data following the [cloning guide](https://github.com/raphael-group/chisel/blob/master/guides/clones.md).

Thank you for your reply. I think I know the reason. The 1000G SNP annotation vcf is somehow missing mutations on chr2q.
