### ISSUE TITLE
Improvement suggestions for figures 

### ISSUE THREAD

**Issue by ivanov-v-v** [raphael-group/chisel#5]
The actual figures that CHISEL outputs are quite different from those in the preprint. For instance, I have not been able to find a figure with a comprehensive visualization of single-cell allele-specific copy numbers, like this one in the paper. 

![image](https://user-images.githubusercontent.com/8493747/69544960-1548f980-0f91-11ea-9c2b-f54d6628dafa.png)

Instead, there are figures like this one (called `totalcn.png`): 

![image](https://user-images.githubusercontent.com/8493747/69545056-49bcb580-0f91-11ea-8424-1e8f970f0fd2.png)

CN of 6 in 100% normal cells makes no sense to me.
I realize that you have probably indexed the CN-tuples like `(0, 0) —> 0`, `(1, 0) —> 1` etc, so that `4` actually means `(1, 1)`, but it would be great if different `(m, p)` configurations with fixed sums were coloured with the shades of the same colour (like in the preprint). Currently, it is very confusing. Figures computed from normal cells still can be interpreted, but only those. If there are many CN events, which is common in cancer, it becomes impossible to understand anything.

**Comment by simozacca** [comment]
Thank you for the interest in our new method, I am happy to help you with the issues that you pointed out! We are sorry for the preliminary version of the repository and the documentation, which is missing some of these details and some guides for quality control. We are in the process of releasing a more detailed version of the documentation soon.

The description of the figures are for now printed directly by CHISEL during the plotting step. In your execution you should have visualized a log message similar to the following:
```
...
[XXX]Plotting total copy numbers: totalcn.png
...
[XXX]Plotting copy-number states: states.png
[XXX]Plotting minor-copy allele: minor.png
```
The following 2 outputs represent the main results of CHISEL:
1. `states.png` represents the allele-specific copy numbers inferred by CHISEL
2. `minor.png` represents the haplotype-specific copy numbers inferred by CHISEL (in the same format as in the preprint)

Therefore, the `total.png` figures that you reported for your results are the TOTAL copy numbers and do NOT correspond to the same preprint figure that you mentioned. Instead, you should be able to find a figure `states.png` which DOES correspond to the ALLELE-SPECIFIC copy numbers reported in the mentioned figure of the manuscript. Please let me know if you do not find this figure, and in this case please report the log messages of CHISEL.

Unfortunately there are two issues in this preliminary version that we are about to fix:
1. The log messages of the plotting step are not using the same terminology of the pre-print;
2. The color bar is not the same of the paper. We are trying to incorporate as an independent figure in the output result but we are encountering some issues in this process. Please refer to the colorbar in the pre-print for simplicity.

I will keep this issue open until these issues will be fixed in the new version.

**Comment by simozacca** [comment]
In addition, I would like to provide some suggestion about your example (this will be better encoded in the guide specific to clustering cells):

Your dataset appears to be characterized be some very clear subclonal structure. As such, you can use `chisel-cloning` command (fast in running time) by changing the parameters `-f` and `-s` to identify these subpopulations. The default values of `-f` and `-s` seem to not be ideal in your case due to a slightly higher variance of the data.

**Comment by ivanov-v-v** [comment]
Thank you very much for your tool and your responsiveness on GitHub. 
Yes, my fault, I actually wanted to ask a question about  `states.png`, where you encode a **tuple** with a **single number** in a way that doesn't seem to be explained anywhere in the README. 
![image](https://user-images.githubusercontent.com/8493747/69826920-7a148600-1215-11ea-9728-616dd078f1e9.png)
Nevertheless, that's ok, I parsed the `calls.tsv` and made the plots I needed myself. 
Waiting for the next release then! 

Also, I do not really understand how to decide on the values of `-f` and `-s` arguments of `chisel-cloning`.  
How have you selected the defaults?

**Comment by simozacca** [comment]
The link with the specific colormap used for the more complicated plots is now provided in the documentation of the `chisel_plotting` command.
